### ISSUE TITLE
Add "View on GitHub" button

### ISSUE THREAD

**Issue by uday03meh** [uday03meh/password-generator#11]
Hi, I would like to add a button like this preferably at the bottom of the page, centered horizontally which links to the GitHub repository of this project.

![image](https://user-images.githubusercontent.com/59679281/197393963-b31f8504-1cba-4a68-97b9-6f167fe66341.png)

You can choose color, background color, hover and active state as you wish, but do share a screenshot here before making a Pull Request.

**Comment by Shivam164** [comment]
Hey @uday03meh, I would like to work on this. Please assign this to me.

**Comment by zainbinfurqan** [comment]
@uday03meh  can i work on it, please?
