### ISSUE TITLE
Improve checkbox design

### ISSUE THREAD

**Issue by uday03meh** [uday03meh/password-generator#4]
If you want to change how checkboxes look or change them to on-off button style or maybe any other idea for checkboxes' design, do comment here to get  assigned

![Screenshot_20221018-165537](https://user-images.githubusercontent.com/59679281/196416919-07b6454d-d966-4b2b-b792-fd2e3e54e6fc.png)

**Comment by jaswindersingh2601** [comment]
Hey @uday03meh assign this issue to me. I will improve this.

**Comment by uday03meh** [comment]
Sure, do share the screenshot for new design here before making the PR

**Comment by uday03meh** [comment]
Hi @jaswindersingh2601, Any updates on this issue?

**Comment by priyanshu2k3** [comment]
hey @uday03meh assign this to me

**Comment by octosapien** [comment]
@uday03meh
I would love to be able to contribute to this .
Could you please assign me this issue ?
