### ISSUE TITLE
Bug: No Checkboxes selected

### ISSUE THREAD

**Issue by sshsrn** [uday03meh/password-generator#9]
When no checkboxes are selected, the website must throw an error or an alert instead of making the text inside the div as **No Boxes Checked**.

Present Behavior: The content of the textbox changes to **No Boxes Checked** and it can still be copied.
Expected Behavior: An alert saying **No Boxes Checked. Check at least a box to generate a random password.**

I am attaching a screen recording of the same for your reference.

https://user-images.githubusercontent.com/62781914/197311174-bb70ee78-a195-4b36-a6e1-e548f1d74b05.mp4

**Comment by sshsrn** [comment]
Kindly assign this issue to me so that I can work on it!

**Comment by uday03meh** [comment]
Thanks for pointing this out!
Assigned.
